### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by mrlt8** [FiveLeavesLeft/repo#1]
Hello and thanks for putting this thing together!

I'm having some trouble installing the new hack.

I believe the `install.sh` from sonic.net is trying to pull the libimp.so from GitHub so it fails since wget on the camera doesn't support https. 

I commented out the GitHub link and it seems to install, but then the camera doesn't come back up after a reboot (solid orange light).

Here's the install log:
```
+ STREAM_HACK_OUTPUT=/tmp/stream_hack.log
+ [ -z  ]
+ WYZE_APP_OUTPUT=/dev/null
+ [ -z /tmp/stream_hack.log ]
+ [ -z  ]
+ STREAM_HACK_VERSION=current
+ [ -z  ]
+ STREAM_HACK_LIB=crb.users.sonic.net/current/libimp.so
+ dir=/configs/stream_hack
+ rm -rf /configs/stream_hack
+ mkdir /configs/stream_hack
+ wget -O /configs/stream_hack/libimp.so crb.users.sonic.net/current/libimp.so
Connecting to crb.users.sonic.net (209.204.190.65:80)
libimp.so            100% |****************************************************************************************************************************| 27780   0:00:00 ETA
+ [ -w /configs/wyze_hack.sh ]
+ wrap /configs/wyze_hack.sh
+ grep stream_hack /configs/wyze_hack.sh
+ echo #!/bin/sh
+ echo export LD_LIBRARY_PATH=/configs/stream_hack:$LD_LIBRARY_PATH
+ echo export STREAM_HACK_PORT=
+ echo export STREAM_HACK_P2P=
+ echo export STREAM_HACK_OUTPUT=/tmp/stream_hack.log
+ echo /configs/wyze_hack.sh.orig >& /dev/null &
+ chmod +x /configs/wyze_hack.sh /configs/wyze_hack.sh.orig
chmod: /configs/wyze_hack.sh.orig: No such file or directory
+ grep -w -c ro
+ grep -w /system /proc/mounts
+ system_read_only=0
+ [ -w /system/init/app_init.sh ]
+ [ 0 == 0 ]
+ wrap /system/init/app_init.sh
+ grep stream_hack /system/init/app_init.sh
+ echo #!/bin/sh
+ echo export LD_LIBRARY_PATH=/configs/stream_hack:$LD_LIBRARY_PATH
+ echo export STREAM_HACK_PORT=
+ echo export STREAM_HACK_P2P=
+ echo export STREAM_HACK_OUTPUT=/tmp/stream_hack.log
+ echo /system/init/app_init.sh.orig >& /dev/null &
+ chmod +x /system/init/app_init.sh /system/init/app_init.sh.orig
chmod: /system/init/app_init.sh.orig: No such file or directory
+ echo Stream hack installed.
Stream hack installed.
```

**Comment by mrlt8** [comment]
Commenting out the ifs on [line 47 and 50](https://github.com/FiveLeavesLeft/WyzeCameraLiveStream/blob/c0ff4ee274666ee36beb8ffe0940a22580023bf6/src/install.sh#L47-L50) in `install.sh` seems to fix the install issue for me.

However, I'm still getting the same issue where the events are not getting uploaded to the Wyze cloud and the motion is not being detected with a green box in live view.

**Comment by FiveLeavesLeft** [comment]
Thanks for the information, I’m on the road today and I will think about this while driving and give you some more thoughts this evening.

I’m currently thinking there may be some remnants of the previous stream hack install around.  And I have too many versions of install.sh in too many different locations.

**Comment by FiveLeavesLeft** [comment]
Could you open an issue on my repo and then we can talk about there instead of cluttering up this space?

I changed the install procedure from the one you installed originally and the current install script. I think what you are seeing is a result of some of the edits done by the orginal install procedure. If you could edit by hand /configs/wyze_hack.sh and /system/init/app_init.sh and remove any lines that refer to stream_hack. Alternatively, you could reinstall the firmware and reinstall wyze_hacks. I’m sorry the two different install procedures put your camera in a weird state. 

Thanks. Let me know if you want me to explain in more detail.

**Comment by mrlt8** [comment]
New install script is working now! Thanks for the fix!

> Could you open an issue on my repo and then we can talk about there instead of cluttering up this space? 

Will do!
