### ISSUE TITLE
Blue Iris

### ISSUE THREAD

**Issue by aechelon** [FiveLeavesLeft/repo#10]
Thanks for putting this together!

Not really an issue, more of a question.  
I got the stream working on a v3 with both vlc and mpv.  Now trying to feed the stream into Blue Iris.  Any idea how to configure a BI camera to accept the h264 stream?

**Comment by FiveLeavesLeft** [comment]
I think someone else figured this out, look in the closed issues.

**Comment by aechelon** [comment]
Found it.  Thank you!
