### ISSUE TITLE
Trying to install on v3 cam firmware version 4.36.0.280

### ISSUE THREAD

**Issue by ikrowni** [FiveLeavesLeft/repo#13]
Been trying to install this onto my v3 cam but it doesnt seem to work. I never hear the camera say "installation begins" like the directions say. After i click yes on my camera it just presents a bunch of dots .............. and my camera blinks blue/red/purple until i press CTRL+C. Ive left it in this state for about 30m and it still never did anything. Any help?

**Comment by FiveLeavesLeft** [comment]
Here's what ./remote_install.sh says for me:

Device type:      Camera (WYZE_CAKP2JFUS)
Device name:      v3
Firmware version: 4.36.0.228
IP Address:       192.168.8.122

Pushing firmware to this device? [y/N]:y
INFO:root:Serving firmware file './firmware.bin' as 'http://192.168.8.104:11808/firmware.bin', md5=5b0282e06199935db0257c3f3288ee6e
192.168.8.122 - - [12/May/2021 18:36:52] "GET /firmware.bin HTTP/1.1" 200 -

Do you get the "INFO:root:Serving firmware file" message? 
Do you get the "GET /firmware.bin HTTP/1.1" message?

Is your computer and camera on the same network?

**Comment by gszakacs** [comment]
I have the same issue. Probably has to do with the fact I don't have a ton of experience with running scripts under linux.
I get the serving firmware file message
But then I do not get the "GET/firmware.bin" message. Instead I get the following:
INFO:root:checking device, mac=XXXXXXXXXXX 
then red+blue (purple) blinking camera status light

My cam (v3 firmware 4.36.0.228) is on the same network as the linux pc (lubuntu 21 +python 3.9.4 + pip 20.3.4)

If I run the sh script as root, I get a warning: /home/lubuntu/.cache/pip is not owned or writeable by the current user, but the script continues just fine. mkdir-d pip folder so the warning doesn't show up anymore, but the firmware still doesn't get pushed to the camera. What python/pip version are you running. Is there a way to add more debugging in the script ?

**Comment by dudududodododedede** [comment]
If you do not see the "GET..." line then you may have a network issue
Do you have a firewall enabled?
Is the camera and your computer on the same subnet (not just the same network)?

**Comment by gszakacs** [comment]
same subnet. camera IP: 192.168.2.173. linux ip: 192.168.2.192
not sure how to disable firewall if one is built in the latest lubuntu release. will check

**Comment by dudududodododedede** [comment]
Note that not hearing "installation begins" is normal on v3 I think (the documentation needs to be updated/there needs to be a bugfix). I've installed this hack on several of my v3 cams and none of them made the "installation begins" alert which I heard on v2 cams. I just wait for the "GET..." line to appear, then wait 5 minutes, then reboot the camera via the wyze app. Then the camera starts responding to telnet and rtsp

**Comment by gszakacs** [comment]
Thanks for trying to figure it out. ufw disabled. still no luck
maybe onto something. trying to ping cam ip from linux and I get a destination host unreachable msg. devices are connected to same wifi AP get IPs assigned from the same DHCP server and IPs are on the same subnet. beats me 
If I connect to another one of my wifi ssids (same router different vlan) now I can ping the camera but now the laptop and the camera are on different subnets. must be a router config issue. I'll try tomorrow with a completely different router with basic settings, no vlans and see if that would help

**Comment by dudududodododedede** [comment]
Unfortunately it sounds like a network issue

The only other things I can think of is to double check the camera IP (my router gives the camera a new IP whenever it restarts for some reason, but the IP shown in the Wyze app is still the old one, until I force-quit the app and start it again)

The other thing to check in ubuntu is the subnet mask, if it's anything other than 255.255.255.0 then there may be a problem

Also is ubuntu running in a VM? Sometimes VMs require funky routing/bridging

**Comment by gszakacs** [comment]
Success. Tried a different wifi router, as basic network config as it gets and now the firmware is being pushed onto the v3 without any issues. I was able to telnet in the camera. The issue must be related to the vlan configuration on my router, and even though the pc was on the same subnet as the camera, the camera didn't get the firmware update for some reason.
Thanks for the idea.

**Comment by ikrowni** [comment]
I've fixed my issue by switching over to an rpi to install wyzehacks. Everything went just fine so it must have just been an issue with Ubuntu through virtualbox.

**Comment by teredactle** [comment]
Just wanted to post here, I was having an issue in CentOS loading the fw, and I turned off the CentOS firewall then the camera connected and grabbed the FW.

CentOS VM in Win10
