### ISSUE TITLE
Wyze not detecting motion when hack is enabled

### ISSUE THREAD

**Issue by mrlt8** [FiveLeavesLeft/repo#2]
Camera firmware: 4.9.6.241
No Wyze Cam Plus subscription.

Direct stream from camera and live view on the Wyze app work great, but motion tagging (green box around motion) is not working and motion events are not getting uploaded to the Wyze cloud when the hack is enabled.

Disabling the hack by commenting out the `LD_LIBRARY_PATH` in  `/system/init/app_init.sh` restores the motion tagging and Wyze cloud events.

**Comment by FiveLeavesLeft** [comment]
Just an update: I can recreate this issue and when I run a minimal program with just the dynamic loading at the start and none of the server or video stuff the problem still exists so it has something to do with with the loader. I did q quick test using LD_PRELOAD but that hung the device. My guess is the loader is not able to load a routine the firmware needs. The log messages from the app are pretty verbal about it which is nice.( Messages saying a function is failing -1, not a message from the ladder saying it couldn’t find a function )  I’m going to busy with other things for a couple of days. On this version of the firmware you can see log messages with “readlog”. The messages are in /tmp/<something>.log .

**Comment by mrlt8** [comment]
Thanks for the update!

Is there an older Wyze firmware version that is compatible with the stream hack?

**Comment by FiveLeavesLeft** [comment]
4.9.6.199 is the most recent that works uploading events.

**Comment by FiveLeavesLeft** [comment]
In the latest release, the stream hack is integrated into WyzeHacks and I believe the events are being reported in the later V2 firmware now.  See the README file.

**Comment by mrlt8** [comment]
> In the latest release, the stream hack is integrated into WyzeHacks and I believe the events are being reported in the later V2 firmware now. See the README file.

Yes, can confirm notifications and motion tagging are working with the latest firmware!
Thanks Charlie!
