### ISSUE TITLE
New issue trying to run ./remote_install.sh, bunch of errors and Broken Pipe..

### ISSUE THREAD

**Issue by teredactle** [FiveLeavesLeft/repo#21]
I had this working before, but today I wanted to add this to 2 more cameras and I'm getting these errors below, ending in Broken Pipe....

Can someone tell me what could be the issue with this?

![wc3](https://user-images.githubusercontent.com/37247773/122591213-a29ae580-d030-11eb-84f2-fcb85fbcee43.jpg)

**Comment by teredactle** [comment]
Nevermind, it's working now, I didn't change anything anywhere but decided to give it a again and now it worked.

**Comment by teredactle** [comment]
Working now

**Comment by noelhibbard** [comment]
I get this sometimes and the fix for me typically is to power cycle the camera.
