### ISSUE TITLE
Can't install on 4.36.3.18

### ISSUE THREAD

**Issue by TonyPuryer** [FiveLeavesLeft/repo#23]
Howdy, and thanks for this software. I'm trying to install this on my v3 with 4.36.3.19 installed. I don't think it's able to install over newer firmware (the dots just keep running in the installer ......, after 20 minutes I thought it was safe to ctrl + C out). The wyze app shows the camera working, and showed a firmware update - from 4.36.2.5 to 4.36.3.18. 

No ports appeared open on the camera (no TCP ports, there were about 8 UDP ports open - definitely no 23 Telnet, no 12345 either) so I'm guessing the camera just rolled back to it's default firmware - or am I doing something wrong, or I'm not installing it correctly? Do I need an sd card installed in the camera perhaps? Thanks for any advice offered.

I then stupidly completed the Wyze firmware update 4.36.2.5 to 4.36.3.18, which then prompted to install 4.36.3.19, which I did. Attempting to install your custom firmware results in the firmware now staying at 4.36.3.19. I believe the newer firmware is locked down and denies 'rolling back' to custom firmware. Perhaps I need to try an SD card update?

**Comment by FiveLeavesLeft** [comment]
From https://github.com/FiveLeavesLeft/WyzeCameraLiveStream/issues/13#issuecomment-840224370 :

> Here's what ./remote_install.sh says for me:
> 
> Device type: Camera (WYZE_CAKP2JFUS)
> Device name: v3
> Firmware version: 4.36.0.228
> IP Address: 192.168.8.122
> 
> Pushing firmware to this device? [y/N]:y
> INFO:root:Serving firmware file './firmware.bin' as 'http://192.168.8.104:11808/firmware.bin', md5=5b0282e06199935db0257c3f3288ee6e
> 192.168.8.122 - - [12/May/2021 18:36:52] "GET /firmware.bin HTTP/1.1" 200 -
> 
> Do you get the "INFO:root:Serving firmware file" message?
> Do you get the "GET /firmware.bin HTTP/1.1" message?
> 

If you never saw the "GET /firmware.bin HTTP/1.1" message, it's a network issue.

**Comment by TonyPuryer** [comment]
Yes, it does show the  "GET /firmware.bin HTTP/1.1" message. The first time I did it, I think I was on 4.36.3.18 firmware, and it appared to 'roll back' to 4.36.2.5. I did attempt to install your software again, but the same thing happened. I then decided to update to 4.36.3.18, which after rebooting then showed a new 4.36.3.19 update, which I also installed. After doing this, it now stays on 4.36.3.19, with no reversion/roll back to 4.36.2.5. Is it possible they've locked down their firmware? 

It does give every sign that it's installing your software. The camera immediately becomes unavailable in the Wyze app when installing it, and the blue/red leds are both lit at the same time on the cam, and it then becomes available again after a few minutes.

I also waited until the camera was available again in the app (but your Python firmware server was still running) and used a Windows 10 laptop to navigate to the server:port, and it downloaded the firmware.bin, so it doesn't appear to be a network issue unfortunately.

I attempted to rollback to an earlier stock version using your script by downloading (from the Wyze website) and copying demo_wcv3_4.36.0.228.bin to the script folder, renaming it to demo_wcv3.bin and modifying the script to serve demo_wcv3.bin instead of firmware.bin, but it didn't work. The camera went offline for a minute or so, and came back with 4.36.3.19. I'll try the sdcard method later today. 

Last edit, I promise! 👍

I downgraded to 4.36.0.228 stock via sdcard method and your software now installs. Telnet server opened on port 23.

Many thanks.

**Comment by FiveLeavesLeft** [comment]
Thanks for letting me know. So the take away is that one has to start with 4.36.0.228 and anything above that doesn't seem to work?

**Comment by TonyPuryer** [comment]
I haven't tried any other firmware versions. I will now as it is quite quick to update the firmware, and it will help contribute something after all my chatter. Rolling out a complete Linux root filesystem in under a minute is not hard work at all.

**Comment by TonyPuryer** [comment]
So the take away is that one has to start with 4.36.0.228 and anything above that doesn't seem to work? Yes.
I removed Wyzehacks, updated to 4.36.0.252, attempted to install Wyzehacks. It took about 3 minutes or blue/red (purple) leds, but when it returned to life ports 23 and 12345 were not reachable/open. Without testing all firmware, it appears firmware 4.36.0.252 is the highest usable.
