### ISSUE TITLE
app_init.sh not linked to wyze_hack.sh?

### ISSUE THREAD

**Issue by mrlt8** [FiveLeavesLeft/repo#3]
I was trying to disable the stream_hack to debug an issue and noticed that editing `/configs/wyze_hack.sh` did not do anything.

Any particular reason why `/system/init/app_init.sh` is not a symbolic link to `/configs/wyze_hack.sh` like the standard WyzeHacks install.

**Comment by FiveLeavesLeft** [comment]
I just noticed that link today. I guess I was using a very old version of wyze hacks on my V2 cameras. 

I’m still not happy with install.sh. I’d like a version that works on v2 and v3 and whether or not wyze hacks is installed.

I also noticed wyze changed their logging with the new firmware, so my old way of looking at iCamera output doesn’t work anymore.

**Comment by FiveLeavesLeft** [comment]
In the latest release, the stream hack is integrated into WyzeHacks, I think this addresses this issue.
