### ISSUE TITLE
SD card not mounting with LiveStream hack

### ISSUE THREAD

**Issue by mrlt8** [FiveLeavesLeft/repo#6]
Hi Charlie, I noticed the wyze app was saying that the camera did not have an SD card installed, and was able to confirmed that nothing was being mounted to `/media/mmc`.

I can see my SD card in `/dev/mmcblk0p1` and was able to manually mount it to `/media/mmc`, but it still doesn’t get notice by the app or persist on reboot.

SD card does get mounted/recognized on the latest vanilla wyze_hacks.
Same issue on two cams with the stream_hack installed.

**Comment by FiveLeavesLeft** [comment]
Interesting. Are the only environment variables set in the config.in file related to the stream hack or are you using some WyzeHacks features too? I've never paid much attention to this, does wyze normally mount /dev/mmcblk0p1 to /media/mmc?

**Comment by mrlt8** [comment]
I only have `export STREAM_HACK=1` enabled. Everything else is commented out.

Vanilla wyze_hacks *without* NFS seems to mount the SD card to /media/mmc.

**Comment by FiveLeavesLeft** [comment]
Ok, I can reproduce this. Existing with WyzeHacks is complicated. First I tried to wrap it, but that didn't work with the latest V2 firmware so I integrated with it but that brings up other issues I need to sort out; it is still catching the mount requests. 

Thanks for pointing this out, I would have never noticed it.

**Comment by FiveLeavesLeft** [comment]
I uploaded a new copy of wyze_hacks_0_5_06.zip which fixes this I believe.

**Comment by mrlt8** [comment]
Can confirm, SD card is working now!
Thanks for the fix @FiveLeavesLeft !
