### ISSUE TITLE
Not compatible with BlueIris

### ISSUE THREAD

**Issue by dudududodododedede** [FiveLeavesLeft/repo#9]
I have no issues viewing the feed in VLC with "vlc http://192.168.0.225:12345 --demux h264"
However BlueIris doesn't seem to play well with the stream

This is my configuration:

192.168.0.202 - BlueIris 4.8.4.7 x64
192.168.0.225 - Wyze Cam v3

![config](https://i.imgur.com/B0SHluH.png)

BlueIris says "No signal"

the stream_hack.log is looping with this:

CRB: Waiting...
CRB: Accept...
CRB: New client: 192.168.0.202
CRB: read failed, stopping client
CRB: New client finished.
CRB: Waiting...
CRB: Accept...
CRB: New client: 192.168.0.202
CRB: read failed, stopping client
CRB: New client finished.
CRB: Waiting...
CRB: Accept...
CRB: New client: 192.168.0.202
CRB: read failed, stopping client
CRB: New client finished.
CRB: Waiting...
CRB: Accept...
CRB: New client: 192.168.0.202
CRB: read failed, stopping client
CRB: New client finished.
CRB: Waiting...
CRB: Accept...
CRB: New client: 192.168.0.202
CRB: read failed, stopping client
CRB: New client finished.
CRB: Waiting...

**Comment by dudududodododedede** [comment]
Nevermind, using these settings in BlueIris made it work:

![config](https://imgur.com/2fwV72p.png)

**Comment by gszakacs** [comment]
Nice to see. This is next step for me, too. Just undecided between Shinobi and BI.
Do you have a free solution for people/pet/object detection that integrates well with BI ?
What is your experience of the video quality between live stream capture on BI vs 1min delayed NFS recording ? Is there benefit recording video one way vs the other ? I like the idea of live streaming but don't mind the 1 min delay if it improves image quality, frame rate, object detection.

**Comment by teredactle** [comment]
I am not able to view the stream in BI at all, nothing I'm trying is working. I'm using BI5.
I am able to view the stream with VLC. Once I try to connect with BI, it kills the stream so that VLC also no longer works until I power cycle the camera....

**Comment by noelhibbard** [comment]
> I am not able to view the stream in BI at all, nothing I'm trying is working. I'm using BI5.
> I am able to view the stream with VLC. Once I try to connect with BI, it kills the stream so that VLC also no longer works until I power cycle the camera....

Same issue for me playing from anything besides VLC. Once I play with something else (ffmpeg for example) it kills the server and then nothing will connect to it, not even VLC.

**Comment by teredactle** [comment]
"When you say "reboot" above, you mean the camera, right? It sounds like the streaming server is not getting the disconnect, which is odd, I've never seen this before. It's a single threaded, single client server."

Running BI v5.2.7.12
Yes, sorry. I'll clarify.
Camera working fine if I launch VLC: vlc http://192.168.5.158:12345 --demux h264
Awesome! I close VLC

I go to BI, add IP of camera and hit Find/Inspect, finds it, adds it as RTSP stream.
Click OK. Stream doesn't work (no signal)
Changed to the above poster's suggestion of HTTP Live Streaming.
Same thing, doesn't work (no signal).

![biwc3](https://user-images.githubusercontent.com/37247773/120331767-1d87a080-c2bc-11eb-97cc-9e152b57effc.jpg)

@dudududodododedede does this work consistently?? 
This is the reason I'm implementing this hack, to get the stream into BI.

**Comment by teredactle** [comment]
I was able to get a live view in BI just now, using the HTTP Live view settings. It worked for less then a minute, I went into the camera settings in BI, then when I exited it killed the stream "No Signal".

Is there a way to make this a bit more stable?

Added: So later yesterday I set it up and it connected. Then disconnected (No Signal). I cleared the stats in BI to check it out today, and it's showing 550 no signal events - that's in a less than 24hr period.  Not sure what causes this, is the stream itself unstable or is it BI?

It's 9:00. Going to disable "RTSP Keep alives" and see if that makes any difference.
-no difference

**Comment by FiveLeavesLeft** [comment]
Another person was having stability issues ( see this thread https://github.com/FiveLeavesLeft/WyzeCameraLiveStream/issues/11 ) and he later declared it “rock solid”. So is it rock solid or unstable? Probably somewhere in the middle.

But if you think the stability issues are in the streaming code and not in BI or your network, you are welcome to look at the code and make suggestions or changes. It’s pretty simple and not much there —see tcp.c and common.c —  the install stuff is way more frail and complex than the streaming code and I’m currently looking at making that more robust.

Thanks.
